# Sidebar navigation

- label: "Todo"
  link: "/"
- label: Review
  link: /review
- label: Optimizations
  items:
    - label: Network Load
      link: /usage/network-load
    - label: React Optimizations
      link: /usage/react-optimizations
    - label: Suggestions
      link: /usage/suggestions
